<?php

namespace Chowhwei\Store\Store;

use Chowhwei\Store\Store;

class AliyunOSS extends Store
{
    public function store(string $bucket, string $content): string
    {
        parent::store($bucket, $content); // TODO: Change the autogenerated stub
    }

    public function get(string $bucket, string $content): string
    {
        parent::get($bucket, $content); // TODO: Change the autogenerated stub
    }

    public function mark(string $bucket, string $hash_key)
    {
        parent::mark($bucket, $hash_key); // TODO: Change the autogenerated stub
    }

    public function unmark(string $bucket, string $hash_key)
    {
        parent::unmark($bucket, $hash_key); // TODO: Change the autogenerated stub
    }
}